# Generated by Django 5.2.7 on 2025-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_series_options_livestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='access_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
