# Generated by Django 5.2.7 on 2025-11-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_subscription_access_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestream',
            options={'verbose_name': 'بث مباشر', 'verbose_name_plural': 'البث المباشر'},
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='allowed_subscriptions',
        ),
        migrations.AddField(
            model_name='livestream',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='البلد'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='access_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
