# Generated by Django 5.2.7 on 2025-11-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_livestream_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='allowed_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='allowed_live_streams', to='content.subscription', verbose_name='الاشتراكات المسموح لها'),
        ),
    ]
