# Generated by Django 5.2.8 on 2025-11-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('is_public', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(blank=True, to='content.genre')),
                ('allowed_subscriptions', models.ManyToManyField(blank=True, related_name='allowed_series', to='content.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('video_url', models.URLField(help_text='رابط ملف .m3u8')),
                ('is_public', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(blank=True, to='content.genre')),
                ('allowed_subscriptions', models.ManyToManyField(blank=True, related_name='allowed_movies', to='content.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('season_number', models.PositiveIntegerField()),
                ('episode_number', models.PositiveIntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('video_url', models.URLField()),
                ('release_date', models.DateField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.series')),
            ],
            options={
                'ordering': ['season_number', 'episode_number'],
                'unique_together': {('series', 'season_number', 'episode_number')},
            },
        ),
    ]
