# Generated by Django 5.2.7 on 2025-11-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم القناة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('thumbnail', models.URLField(blank=True, verbose_name='رابط الصورة المصغرة')),
                ('stream_url', models.URLField(help_text='رابط البث المباشر بصيغة .m3u8', verbose_name='رابط البث')),
                ('is_public', models.BooleanField(default=True, verbose_name='عام؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('allowed_subscriptions', models.ManyToManyField(blank=True, related_name='allowed_live_streams', to='content.subscription', verbose_name='الاشتراكات المسموح لها')),
            ],
            options={
                'verbose_name': 'بث مباشر',
                'verbose_name_plural': 'البثوص المباشرة',
            },
        ),
    ]
